HYPERPARAMETER TUNING TYPES:
1. GridSearchCV
2. RandomizedSearchCV

Importing dependencies

In [4]:
import numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

Loading the dataset

In [5]:
breast_cancer_dataset = sklearn.datasets.load_breast_cancer()

In [6]:
print(breast_cancer_dataset)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [9]:
df = pd.DataFrame(breast_cancer_dataset.data, columns = breast_cancer_dataset.feature_names)

In [10]:
df.head()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

Adding the target col to the dataframe

In [11]:
df['label']=breast_cancer_dataset.target

In [12]:
df.head()

mean radius  mean texture  mean perimeter  ...  worst symmetry  worst fractal dimension  label
0        17.99         10.38          122.80  ...          0.4601                  0.11890      0
1        20.57         17.77          132.90  ...          0.2750                  0.08902      0
2        19.69         21.25          130.00  ...          0.3613                  0.08758      0
3        11.42         20.38           77.58  ...          0.6638                  0.17300      0
4        20.29         14.34          135.10  ...          0.2364                  0.07678      0

[5 rows x 31 columns]

In [13]:
df.shape

(569, 31)

In [14]:
df.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
label                      0
dtype: int64

In [15]:
df['label'].value_counts()

label
1    357
0    212
Name: count, dtype: int64

Seperating the feture and the target

In [16]:
X = df.drop(columns='label', axis=1)
Y = df['label']

In [17]:
print(X)
print(Y)

     mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]
0      0
1      0
2      0
3      0
4      0
      

Converting datas to array

In [18]:
X = np.asarray(X)
Y = np.asarray(Y)

In [19]:
print(X)
print(Y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

# GRID_SEARCH_CV



It is used to determine the best parameter for the model

In [20]:
# loading SVC model
model = SVC()

In [21]:
# hyperparameter
parameters = {
              'kernel':['linear', 'rbf', 'poly', 'sigmoid'],
              'C' : [1, 5, 10, 20]
              }

In [23]:
# grid search
classifier = GridSearchCV(model, parameters, cv=5)

In [24]:
# fitting the data to the model
classifier.fit(X,Y)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 5, 10, 20],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid']})

In [25]:
classifier.cv_results_

{'mean_fit_time': array([1.63299985e+00, 5.13558388e-03, 3.81383896e-03, 1.48824692e-02,
        4.21862640e+00, 1.95193291e-02, 1.62589073e-02, 5.39399624e-02,
        5.70203586e+00, 4.14991379e-03, 4.28900719e-03, 1.35763168e-02,
        7.46755176e+00, 4.41660881e-03, 4.84089851e-03, 1.37487888e-02]),
 'std_fit_time': array([7.43391208e-01, 9.44444655e-04, 1.41609124e-04, 5.58587441e-04,
        1.06923918e+00, 5.80489122e-03, 5.24065963e-03, 1.10596146e-02,
        1.92428643e+00, 8.96032721e-05, 1.24021449e-04, 7.41564715e-04,
        2.23768621e+00, 3.20349999e-04, 2.71975576e-04, 8.45142023e-04]),
 'mean_score_time': array([0.00189214, 0.00198317, 0.00129204, 0.00385637, 0.0039166 ,
        0.01117163, 0.00361609, 0.01506824, 0.00139461, 0.00167093,
        0.0012877 , 0.00359616, 0.00126309, 0.0017365 , 0.00131936,
        0.00379748]),
 'std_score_time': array([6.26274834e-04, 8.23479963e-05, 2.44303552e-05, 8.98286286e-05,
        4.57214334e-03, 4.97841701e-03, 2.90291304e-

In [26]:
# best parameter
best_params = classifier.best_params_
print(best_params)

{'C': 10, 'kernel': 'linear'}


In [27]:
# determining highest accuracy
highest_accuracy = classifier.best_score_
print(highest_accuracy)

0.9525694767893185


In [28]:
# loading the results to pd dataframe
result = pd.DataFrame(classifier.cv_results_)

In [29]:
result.head()

mean_fit_time  std_fit_time  mean_score_time  ...  mean_test_score  std_test_score rank_test_score
0       1.633000      0.743391         0.001892  ...         0.945536        0.018689               4
1       0.005136      0.000944         0.001983  ...         0.912172        0.035444              11
2       0.003814      0.000142         0.001292  ...         0.908663        0.039382              12
3       0.014882      0.000559         0.003856  ...         0.460441        0.050253              13
4       4.218626      1.069239         0.003917  ...         0.950815        0.016216               2

[5 rows x 15 columns]

In [30]:
grid_search_result = result[['param_C','param_kernel','mean_test_score' ]]

In [32]:
grid_search_result

param_C param_kernel  mean_test_score
0         1       linear         0.945536
1         1          rbf         0.912172
2         1         poly         0.908663
3         1      sigmoid         0.460441
4         5       linear         0.950815
5         5          rbf         0.931501
6         5         poly         0.922729
7         5      sigmoid         0.411178
8        10       linear         0.952569
9        10          rbf         0.922714
10       10         poly         0.920975
11       10      sigmoid         0.402391
12       20       linear         0.949061
13       20          rbf         0.920944
14       20         poly         0.919221
15       20      sigmoid         0.398867

Highest accuracy = 95.2 %   
Best parameter:   
    

*   C = 10
*   Kernel = linear




# RANDOMIZED_SEARCH_CV

Randomly finds best parameters

In [33]:
model = SVC()

In [34]:
# hyperparameter
parameters = {
              'kernel':['linear', 'rbf', 'poly', 'sigmoid'],
              'C' : [1, 5, 10, 20]
              }

In [35]:
# randomized search
classifier = RandomizedSearchCV(model, parameters, cv=5)

In [36]:
# fitting the data to the model
classifier.fit(X, Y)

RandomizedSearchCV(cv=5, estimator=SVC(),
                   param_distributions={'C': [1, 5, 10, 20],
                                        'kernel': ['linear', 'rbf', 'poly',
                                                   'sigmoid']})

In [37]:
classifier.cv_results_

{'mean_fit_time': array([5.34820557e-03, 8.93013930e+00, 5.85408301e+00, 4.69355583e-03,
        4.15744781e-03, 4.40926552e-03, 1.38464451e-02, 4.92858887e-03,
        4.15410995e-03, 3.98187637e-03]),
 'std_fit_time': array([1.42138933e-03, 1.61735198e+00, 2.27500771e+00, 1.22727584e-04,
        1.30683537e-04, 5.93919132e-04, 7.07924968e-04, 5.10714746e-04,
        2.29945572e-04, 3.91119627e-04]),
 'mean_score_time': array([0.00156302, 0.00128469, 0.00148306, 0.00199862, 0.00168638,
        0.00173278, 0.00360909, 0.00145569, 0.0014493 , 0.00128512]),
 'std_score_time': array([4.27381045e-04, 3.22983177e-05, 2.33223370e-04, 4.93528532e-05,
        7.75394109e-05, 5.62555496e-05, 3.33617713e-05, 2.07226681e-04,
        1.43719178e-04, 3.65455788e-05]),
 'param_kernel': masked_array(data=['poly', 'linear', 'linear', 'rbf', 'rbf', 'rbf',
                    'sigmoid', 'poly', 'poly', 'poly'],
              mask=[False, False, False, False, False, False, False, False,
                 

In [38]:
classifier.best_params_

{'kernel': 'linear', 'C': 10}

In [39]:
classifier.best_score_

np.float64(0.9525694767893185)

In [40]:
# loading the result to the pd dataframe
result = pd.DataFrame(classifier.cv_results_)

In [41]:
result.head()

mean_fit_time  std_fit_time  mean_score_time  ...  mean_test_score std_test_score  rank_test_score
0       0.005348      0.001421         0.001563  ...         0.920975       0.024701                6
1       8.930139      1.617352         0.001285  ...         0.949061       0.012816                2
2       5.854083      2.275008         0.001483  ...         0.952569       0.014200                1
3       0.004694      0.000123         0.001999  ...         0.912172       0.035444                8
4       0.004157      0.000131         0.001686  ...         0.922714       0.027879                5

[5 rows x 15 columns]

In [42]:
randomized_search_result = result[['param_C','param_kernel','mean_test_score']]

In [43]:
randomized_search_result

param_C param_kernel  mean_test_score
0       10         poly         0.920975
1       20       linear         0.949061
2       10       linear         0.952569
3        1          rbf         0.912172
4       10          rbf         0.922714
5        5          rbf         0.931501
6       10      sigmoid         0.402391
7       20         poly         0.919221
8        1         poly         0.908663
9        5         poly         0.922729

Highest accuracy = 95.2 %   
Best parameters:   


*   C = 10
*   Kernek = linear

